remove bundled pyh5md
espressopp/espressopp pull request #363
Opened 2021-04-29 09:28 UTC by XzzX

pyh5md can be installed via pip, no need to bundle it

2021-04-29 14:49 UTC, junghans requested changes
CMake needs to check if the `pyh5md` module is actually there.

2021-04-29 15:15 UTC, junghans commented
Aren't the tests using pyh5md?

2021-04-29 15:30 UTC, XzzX commented
> Aren't the tests using pyh5md?

Yes, the python tests do.

2021-04-29 15:55 UTC, XzzX commented
I reworked the readme and introduced a requirements.txt file. I think something like `could not find xxx` while executing the tests is as good as checking it via CMake.

2021-04-29 17:58 UTC, junghans commented
yeah, as long as the test don't fail, but get skipped everything is fine.

2021-04-30 07:25 UTC, XzzX commented
> yeah, as long as the test don't fail, but get skipped everything is fine.

They will fail. But I think this is ok since you do not meet the dependencies. C++ will also not build if you do not have the dependencies installed.

2021-04-30 14:28 UTC, junghans commented
> > yeah, as long as the test don't fail, but get skipped everything is fine.
> 
> They will fail. But I think this is ok since you do not meet the dependencies. C++ will also not build if you do not have the dependencies installed.

The C++ dependencies are checked at CMake time, right? We should just exclude the tests for which the deps are missing, otherwise we will get a lot of spurious failures.

2021-04-30 14:37 UTC, XzzX commented
> > > yeah, as long as the test don't fail, but get skipped everything is fine.
> > 
> > 
> > They will fail. But I think this is ok since you do not meet the dependencies. C++ will also not build if you do not have the dependencies installed.
> 
> The C++ dependencies are checked at CMake time, right? We should just exclude the tests for which the deps are missing, otherwise we will get a lot of spurious failures.

Why? That's how Python works. Everything is checked at runtime. Something like `could not find h5py` is a pretty clear indication that you do not meet all dependencies. Deactivating tests just gives you an incorrect feeling that everything is ok.

2021-04-30 15:28 UTC, XzzX commented
> I am thinking more from the C++ side, where `configure`, `make`, `make test` is the normal workflow. 

Yes, correct, and this works without a problem for the C++ side of the code, namely `_espressopp`.

Problems rise due to the hand-crafted integration of the Python frontend `espressopp` into cmake. Requiring hacks like `TEST_ENV` and calling the Python interpreter explicitly. Since `espressopp` is using `unittest` the correct way to integrate tests would be via `unittest discovery`, however, this does not work since `espressopp` does not follow the `unittest` guidelines.

Furthermore, a Python user should be used to missing package errors and know how to deal with them as this is classic Python business.

> I even have seen a couple of `setup.py` that check for dependencies and warn about reduced functionality. 

Yes, pythonic and very similar to my `requirements.txt`. Could be done but seems like no one cared about that.

> I think for our user community we have to make things as easy as possible hence I vote for a nice readable message at configure time.

That's not how Python works. As a Python user I do not know what `configure` is. I vote for implementing things in the ideology the programming language has. In my opinion this makes it easier for new users as the programming language behaves like they expect it. For Python this means, if you have an error in your script you will be notified at runtime, true for all Python errors.

2021-04-30 15:34 UTC, junghans commented
Go ahead, I am not the one that has to provide user support ;-)

2021-04-30 15:49 UTC, XzzX commented on README.md
> +#Dependencies
fixed

2021-05-01 10:12 UTC, jkrajniak approved these changes

2021-05-07 03:44 UTC, junghans approved these changes

2021-05-07 07:46 UTC, merged